print('Seja bem vindo, primeiramente preciso saber o seu nome !')
nome1 = input('Qual o seu nome ?')
print('Prazer em te conhecer,', nome1, '!')
print('Agora preciso de algumas informações ! Por favor !')
dia = input('Qual o dia em que nasceu?')
mes = input('Qual o mês?')
ano = input('Agora, qual o ano?')
peso = input('E quanto você pesa?')
print('Então você nasceu em', dia, 'de', mes, 'no ano de', ano, 'e tem', peso, 'kg')
print('Obrigado pelas informações', nome1, 'foi uma gentileza da sua parte !')
