br = ('-')
br2 = ('=')
print(br2 * 70)
print('MÁQUINA DE DESCONTOS')
print(br2 * 70)
print('\nINSTRUÇÕES: DIGITE SOMENTE NÚMEROS, PARA EVITAR ERRO !')
print(br * 70)
valor = float(input('Qual o valor do produto, que está querendo ?:'))
desconto = valor - (valor * 5 / 100)
print('\nFornecendo o desconto !')
print(f'O PRODUTO DE R${valor} REAIS, COM 5% DE DESCONTO ESTÁ {desconto:.2f}!')
print(f'\nVALOR TOTAL DO PRODUTO:R${desconto:.2f} REAIS')
print(br2 * 70)
